package ac.uk.icl.dell.gwt.canvasfont.client;
import ac.uk.icl.dell.gwt.canvas.client.Font;
import ac.uk.icl.dell.gwt.canvas.client.FontCharacter;
import ac.uk.icl.dell.gwt.canvas.client.FontCharacterException;
import ac.uk.icl.dell.gwt.canvas.client.FontPoint;
import ac.uk.icl.dell.gwt.canvas.client.FontSegment;



@SuppressWarnings("serial")
public class Simplex extends Font {

	public Simplex() {
		super("Simplex");
		try {
			init();
		} catch (FontCharacterException e) {
			e.printStackTrace();
		}
	}

	private void init() throws FontCharacterException {
		FontCharacter fontCharacter;
		FontSegment fontSegment;
		fontCharacter = new FontCharacter(' ', 16.0);
		this.add(fontCharacter);
		fontCharacter = new FontCharacter('!', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 18.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontCharacter = new FontCharacter('"', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(12.0, 11.0));
		fontCharacter = new FontCharacter('#', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(11.0, 0.0));
		fontSegment.add(new FontPoint(4.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 0.0));
		fontSegment.add(new FontPoint(10.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 13.0));
		fontSegment.add(new FontPoint(18.0, 13.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontCharacter = new FontCharacter('$', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 0.0));
		fontSegment.add(new FontPoint(8.0, 29.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(12.0, 0.0));
		fontSegment.add(new FontPoint(12.0, 29.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 5.0));
		fontSegment.add(new FontPoint(3.0, 7.0));
		fontSegment.add(new FontPoint(3.0, 9.0));
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(5.0, 12.0));
		fontSegment.add(new FontPoint(7.0, 13.0));
		fontSegment.add(new FontPoint(13.0, 15.0));
		fontSegment.add(new FontPoint(15.0, 16.0));
		fontSegment.add(new FontPoint(16.0, 17.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(12.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(3.0, 22.0));
		fontCharacter = new FontCharacter('%', 24.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(21.0, 4.0));
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(10.0, 6.0));
		fontSegment.add(new FontPoint(10.0, 8.0));
		fontSegment.add(new FontPoint(9.0, 10.0));
		fontSegment.add(new FontPoint(7.0, 11.0));
		fontSegment.add(new FontPoint(5.0, 11.0));
		fontSegment.add(new FontPoint(3.0, 9.0));
		fontSegment.add(new FontPoint(3.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 5.0));
		fontSegment.add(new FontPoint(6.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(10.0, 5.0));
		fontSegment.add(new FontPoint(13.0, 6.0));
		fontSegment.add(new FontPoint(16.0, 6.0));
		fontSegment.add(new FontPoint(19.0, 5.0));
		fontSegment.add(new FontPoint(21.0, 4.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 18.0));
		fontSegment.add(new FontPoint(15.0, 19.0));
		fontSegment.add(new FontPoint(14.0, 21.0));
		fontSegment.add(new FontPoint(14.0, 23.0));
		fontSegment.add(new FontPoint(16.0, 25.0));
		fontSegment.add(new FontPoint(18.0, 25.0));
		fontSegment.add(new FontPoint(20.0, 24.0));
		fontSegment.add(new FontPoint(21.0, 22.0));
		fontSegment.add(new FontPoint(21.0, 20.0));
		fontSegment.add(new FontPoint(19.0, 18.0));
		fontSegment.add(new FontPoint(17.0, 18.0));
		fontCharacter = new FontCharacter('&', 26.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(23.0, 13.0));
		fontSegment.add(new FontPoint(23.0, 12.0));
		fontSegment.add(new FontPoint(22.0, 11.0));
		fontSegment.add(new FontPoint(21.0, 11.0));
		fontSegment.add(new FontPoint(20.0, 12.0));
		fontSegment.add(new FontPoint(19.0, 14.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 23.0));
		fontSegment.add(new FontPoint(3.0, 21.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 17.0));
		fontSegment.add(new FontPoint(5.0, 16.0));
		fontSegment.add(new FontPoint(12.0, 12.0));
		fontSegment.add(new FontPoint(13.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 9.0));
		fontSegment.add(new FontPoint(14.0, 7.0));
		fontSegment.add(new FontPoint(13.0, 5.0));
		fontSegment.add(new FontPoint(11.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 5.0));
		fontSegment.add(new FontPoint(8.0, 7.0));
		fontSegment.add(new FontPoint(8.0, 9.0));
		fontSegment.add(new FontPoint(9.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 15.0));
		fontSegment.add(new FontPoint(16.0, 22.0));
		fontSegment.add(new FontPoint(18.0, 24.0));
		fontSegment.add(new FontPoint(20.0, 25.0));
		fontSegment.add(new FontPoint(22.0, 25.0));
		fontSegment.add(new FontPoint(23.0, 24.0));
		fontSegment.add(new FontPoint(23.0, 23.0));
		fontCharacter = new FontCharacter('\'', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 10.0));
		fontCharacter = new FontCharacter('(', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(11.0, 0.0));
		fontSegment.add(new FontPoint(9.0, 2.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 9.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(4.0, 18.0));
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontSegment.add(new FontPoint(7.0, 27.0));
		fontSegment.add(new FontPoint(9.0, 30.0));
		fontSegment.add(new FontPoint(11.0, 32.0));
		fontCharacter = new FontCharacter(')', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 0.0));
		fontSegment.add(new FontPoint(5.0, 2.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(9.0, 9.0));
		fontSegment.add(new FontPoint(10.0, 14.0));
		fontSegment.add(new FontPoint(10.0, 18.0));
		fontSegment.add(new FontPoint(9.0, 23.0));
		fontSegment.add(new FontPoint(7.0, 27.0));
		fontSegment.add(new FontPoint(5.0, 30.0));
		fontSegment.add(new FontPoint(3.0, 32.0));
		fontCharacter = new FontCharacter('*', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 16.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 7.0));
		fontSegment.add(new FontPoint(13.0, 13.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(13.0, 7.0));
		fontSegment.add(new FontPoint(3.0, 13.0));
		fontCharacter = new FontCharacter('+', 26.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(13.0, 7.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(22.0, 16.0));
		fontCharacter = new FontCharacter(',', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 28.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 28.0));
		fontSegment.add(new FontPoint(4.0, 29.0));
		fontCharacter = new FontCharacter('-', 26.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(22.0, 16.0));
		fontCharacter = new FontCharacter('.', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontCharacter = new FontCharacter('/', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(20.0, 0.0));
		fontSegment.add(new FontPoint(2.0, 32.0));
		fontCharacter = new FontCharacter('0', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(6.0, 5.0));
		fontSegment.add(new FontPoint(4.0, 8.0));
		fontSegment.add(new FontPoint(3.0, 13.0));
		fontSegment.add(new FontPoint(3.0, 16.0));
		fontSegment.add(new FontPoint(4.0, 21.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(14.0, 24.0));
		fontSegment.add(new FontPoint(16.0, 21.0));
		fontSegment.add(new FontPoint(17.0, 16.0));
		fontSegment.add(new FontPoint(17.0, 13.0));
		fontSegment.add(new FontPoint(16.0, 8.0));
		fontSegment.add(new FontPoint(14.0, 5.0));
		fontSegment.add(new FontPoint(11.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontCharacter = new FontCharacter('1', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(6.0, 8.0));
		fontSegment.add(new FontPoint(8.0, 7.0));
		fontSegment.add(new FontPoint(11.0, 4.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontCharacter = new FontCharacter('2', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 9.0));
		fontSegment.add(new FontPoint(4.0, 8.0));
		fontSegment.add(new FontPoint(5.0, 6.0));
		fontSegment.add(new FontPoint(6.0, 5.0));
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(14.0, 5.0));
		fontSegment.add(new FontPoint(15.0, 6.0));
		fontSegment.add(new FontPoint(16.0, 8.0));
		fontSegment.add(new FontPoint(16.0, 10.0));
		fontSegment.add(new FontPoint(15.0, 12.0));
		fontSegment.add(new FontPoint(13.0, 15.0));
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontSegment.add(new FontPoint(17.0, 25.0));
		fontCharacter = new FontCharacter('3', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(16.0, 4.0));
		fontSegment.add(new FontPoint(10.0, 12.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 13.0));
		fontSegment.add(new FontPoint(16.0, 14.0));
		fontSegment.add(new FontPoint(17.0, 17.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(16.0, 22.0));
		fontSegment.add(new FontPoint(14.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 23.0));
		fontSegment.add(new FontPoint(3.0, 21.0));
		fontCharacter = new FontCharacter('4', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(3.0, 18.0));
		fontSegment.add(new FontPoint(18.0, 18.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontCharacter = new FontCharacter('5', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 13.0));
		fontSegment.add(new FontPoint(5.0, 12.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 12.0));
		fontSegment.add(new FontPoint(16.0, 14.0));
		fontSegment.add(new FontPoint(17.0, 17.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(16.0, 22.0));
		fontSegment.add(new FontPoint(14.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 23.0));
		fontSegment.add(new FontPoint(3.0, 21.0));
		fontCharacter = new FontCharacter('6', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(16.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(10.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 8.0));
		fontSegment.add(new FontPoint(4.0, 13.0));
		fontSegment.add(new FontPoint(4.0, 18.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(7.0, 24.0));
		fontSegment.add(new FontPoint(10.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(14.0, 24.0));
		fontSegment.add(new FontPoint(16.0, 22.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(17.0, 18.0));
		fontSegment.add(new FontPoint(16.0, 15.0));
		fontSegment.add(new FontPoint(14.0, 13.0));
		fontSegment.add(new FontPoint(11.0, 12.0));
		fontSegment.add(new FontPoint(10.0, 12.0));
		fontSegment.add(new FontPoint(7.0, 13.0));
		fontSegment.add(new FontPoint(5.0, 15.0));
		fontSegment.add(new FontPoint(4.0, 18.0));
		fontCharacter = new FontCharacter('7', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 4.0));
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontCharacter = new FontCharacter('8', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 5.0));
		fontSegment.add(new FontPoint(4.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 9.0));
		fontSegment.add(new FontPoint(5.0, 11.0));
		fontSegment.add(new FontPoint(7.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 13.0));
		fontSegment.add(new FontPoint(14.0, 14.0));
		fontSegment.add(new FontPoint(16.0, 16.0));
		fontSegment.add(new FontPoint(17.0, 18.0));
		fontSegment.add(new FontPoint(17.0, 21.0));
		fontSegment.add(new FontPoint(16.0, 23.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(12.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 23.0));
		fontSegment.add(new FontPoint(3.0, 21.0));
		fontSegment.add(new FontPoint(3.0, 18.0));
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(6.0, 14.0));
		fontSegment.add(new FontPoint(9.0, 13.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 11.0));
		fontSegment.add(new FontPoint(16.0, 9.0));
		fontSegment.add(new FontPoint(16.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontCharacter = new FontCharacter('9', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(16.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 16.0));
		fontSegment.add(new FontPoint(10.0, 17.0));
		fontSegment.add(new FontPoint(9.0, 17.0));
		fontSegment.add(new FontPoint(6.0, 16.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 11.0));
		fontSegment.add(new FontPoint(3.0, 10.0));
		fontSegment.add(new FontPoint(4.0, 7.0));
		fontSegment.add(new FontPoint(6.0, 5.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(10.0, 4.0));
		fontSegment.add(new FontPoint(13.0, 5.0));
		fontSegment.add(new FontPoint(15.0, 7.0));
		fontSegment.add(new FontPoint(16.0, 11.0));
		fontSegment.add(new FontPoint(16.0, 16.0));
		fontSegment.add(new FontPoint(15.0, 21.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(10.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontCharacter = new FontCharacter(':', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 12.0));
		fontSegment.add(new FontPoint(5.0, 13.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(5.0, 11.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontCharacter = new FontCharacter(';', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 12.0));
		fontSegment.add(new FontPoint(5.0, 13.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(5.0, 11.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 23.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 28.0));
		fontSegment.add(new FontPoint(4.0, 29.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 28.0));
		fontCharacter = new FontCharacter('<', 24.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(20.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(20.0, 25.0));
		fontCharacter = new FontCharacter('=', 26.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 13.0));
		fontSegment.add(new FontPoint(22.0, 13.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 19.0));
		fontSegment.add(new FontPoint(22.0, 19.0));
		fontCharacter = new FontCharacter('>', 24.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 7.0));
		fontSegment.add(new FontPoint(20.0, 16.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontCharacter = new FontCharacter('?', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 9.0));
		fontSegment.add(new FontPoint(3.0, 8.0));
		fontSegment.add(new FontPoint(4.0, 6.0));
		fontSegment.add(new FontPoint(5.0, 5.0));
		fontSegment.add(new FontPoint(7.0, 4.0));
		fontSegment.add(new FontPoint(11.0, 4.0));
		fontSegment.add(new FontPoint(13.0, 5.0));
		fontSegment.add(new FontPoint(14.0, 6.0));
		fontSegment.add(new FontPoint(15.0, 8.0));
		fontSegment.add(new FontPoint(15.0, 10.0));
		fontSegment.add(new FontPoint(14.0, 12.0));
		fontSegment.add(new FontPoint(13.0, 13.0));
		fontSegment.add(new FontPoint(9.0, 15.0));
		fontSegment.add(new FontPoint(9.0, 18.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 23.0));
		fontSegment.add(new FontPoint(8.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(10.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 23.0));
		fontCharacter = new FontCharacter('@', 27.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(18.0, 12.0));
		fontSegment.add(new FontPoint(17.0, 10.0));
		fontSegment.add(new FontPoint(15.0, 9.0));
		fontSegment.add(new FontPoint(12.0, 9.0));
		fontSegment.add(new FontPoint(10.0, 10.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 14.0));
		fontSegment.add(new FontPoint(8.0, 17.0));
		fontSegment.add(new FontPoint(9.0, 19.0));
		fontSegment.add(new FontPoint(11.0, 20.0));
		fontSegment.add(new FontPoint(14.0, 20.0));
		fontSegment.add(new FontPoint(16.0, 19.0));
		fontSegment.add(new FontPoint(17.0, 17.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(12.0, 9.0));
		fontSegment.add(new FontPoint(10.0, 11.0));
		fontSegment.add(new FontPoint(9.0, 14.0));
		fontSegment.add(new FontPoint(9.0, 17.0));
		fontSegment.add(new FontPoint(10.0, 19.0));
		fontSegment.add(new FontPoint(11.0, 20.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(18.0, 9.0));
		fontSegment.add(new FontPoint(17.0, 17.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(19.0, 20.0));
		fontSegment.add(new FontPoint(21.0, 20.0));
		fontSegment.add(new FontPoint(23.0, 18.0));
		fontSegment.add(new FontPoint(24.0, 15.0));
		fontSegment.add(new FontPoint(24.0, 13.0));
		fontSegment.add(new FontPoint(23.0, 10.0));
		fontSegment.add(new FontPoint(22.0, 8.0));
		fontSegment.add(new FontPoint(20.0, 6.0));
		fontSegment.add(new FontPoint(18.0, 5.0));
		fontSegment.add(new FontPoint(15.0, 4.0));
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 5.0));
		fontSegment.add(new FontPoint(7.0, 6.0));
		fontSegment.add(new FontPoint(5.0, 8.0));
		fontSegment.add(new FontPoint(4.0, 10.0));
		fontSegment.add(new FontPoint(3.0, 13.0));
		fontSegment.add(new FontPoint(3.0, 16.0));
		fontSegment.add(new FontPoint(4.0, 19.0));
		fontSegment.add(new FontPoint(5.0, 21.0));
		fontSegment.add(new FontPoint(7.0, 23.0));
		fontSegment.add(new FontPoint(9.0, 24.0));
		fontSegment.add(new FontPoint(12.0, 25.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontSegment.add(new FontPoint(18.0, 24.0));
		fontSegment.add(new FontPoint(20.0, 23.0));
		fontSegment.add(new FontPoint(21.0, 22.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(19.0, 9.0));
		fontSegment.add(new FontPoint(18.0, 17.0));
		fontSegment.add(new FontPoint(18.0, 19.0));
		fontSegment.add(new FontPoint(19.0, 20.0));
		fontCharacter = new FontCharacter('A', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(1.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(17.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 17.0));
		fontSegment.add(new FontPoint(14.0, 17.0));
		fontCharacter = new FontCharacter('B', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(16.0, 5.0));
		fontSegment.add(new FontPoint(17.0, 6.0));
		fontSegment.add(new FontPoint(18.0, 8.0));
		fontSegment.add(new FontPoint(18.0, 10.0));
		fontSegment.add(new FontPoint(17.0, 12.0));
		fontSegment.add(new FontPoint(16.0, 13.0));
		fontSegment.add(new FontPoint(13.0, 14.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 14.0));
		fontSegment.add(new FontPoint(16.0, 15.0));
		fontSegment.add(new FontPoint(17.0, 16.0));
		fontSegment.add(new FontPoint(18.0, 18.0));
		fontSegment.add(new FontPoint(18.0, 21.0));
		fontSegment.add(new FontPoint(17.0, 23.0));
		fontSegment.add(new FontPoint(16.0, 24.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontCharacter = new FontCharacter('C', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(18.0, 9.0));
		fontSegment.add(new FontPoint(17.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 9.0));
		fontSegment.add(new FontPoint(3.0, 12.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(4.0, 20.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(7.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(18.0, 20.0));
		fontCharacter = new FontCharacter('D', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(11.0, 4.0));
		fontSegment.add(new FontPoint(14.0, 5.0));
		fontSegment.add(new FontPoint(16.0, 7.0));
		fontSegment.add(new FontPoint(17.0, 9.0));
		fontSegment.add(new FontPoint(18.0, 12.0));
		fontSegment.add(new FontPoint(18.0, 17.0));
		fontSegment.add(new FontPoint(17.0, 20.0));
		fontSegment.add(new FontPoint(16.0, 22.0));
		fontSegment.add(new FontPoint(14.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontCharacter = new FontCharacter('E', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(12.0, 14.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment.add(new FontPoint(17.0, 25.0));
		fontCharacter = new FontCharacter('F', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(12.0, 14.0));
		fontCharacter = new FontCharacter('G', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(18.0, 9.0));
		fontSegment.add(new FontPoint(17.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 9.0));
		fontSegment.add(new FontPoint(3.0, 12.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(4.0, 20.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(7.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(18.0, 20.0));
		fontSegment.add(new FontPoint(18.0, 17.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(13.0, 17.0));
		fontSegment.add(new FontPoint(18.0, 17.0));
		fontCharacter = new FontCharacter('H', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(18.0, 4.0));
		fontSegment.add(new FontPoint(18.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(18.0, 14.0));
		fontCharacter = new FontCharacter('I', 8.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontCharacter = new FontCharacter('J', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(12.0, 20.0));
		fontSegment.add(new FontPoint(11.0, 23.0));
		fontSegment.add(new FontPoint(10.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(3.0, 23.0));
		fontSegment.add(new FontPoint(2.0, 20.0));
		fontSegment.add(new FontPoint(2.0, 18.0));
		fontCharacter = new FontCharacter('K', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(18.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 18.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 13.0));
		fontSegment.add(new FontPoint(18.0, 25.0));
		fontCharacter = new FontCharacter('L', 17.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment.add(new FontPoint(16.0, 25.0));
		fontCharacter = new FontCharacter('M', 24.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(12.0, 19.0));
		fontSegment.add(new FontPoint(20.0, 4.0));
		fontSegment.add(new FontPoint(20.0, 25.0));
		fontCharacter = new FontCharacter('N', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(18.0, 25.0));
		fontSegment.add(new FontPoint(18.0, 4.0));
		fontCharacter = new FontCharacter('O', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 9.0));
		fontSegment.add(new FontPoint(3.0, 12.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(4.0, 20.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(7.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(18.0, 20.0));
		fontSegment.add(new FontPoint(19.0, 17.0));
		fontSegment.add(new FontPoint(19.0, 12.0));
		fontSegment.add(new FontPoint(18.0, 9.0));
		fontSegment.add(new FontPoint(17.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontCharacter = new FontCharacter('P', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(16.0, 5.0));
		fontSegment.add(new FontPoint(17.0, 6.0));
		fontSegment.add(new FontPoint(18.0, 8.0));
		fontSegment.add(new FontPoint(18.0, 11.0));
		fontSegment.add(new FontPoint(17.0, 13.0));
		fontSegment.add(new FontPoint(16.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 15.0));
		fontSegment.add(new FontPoint(4.0, 15.0));
		fontCharacter = new FontCharacter('Q', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 7.0));
		fontSegment.add(new FontPoint(4.0, 9.0));
		fontSegment.add(new FontPoint(3.0, 12.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(4.0, 20.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(7.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 25.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(18.0, 20.0));
		fontSegment.add(new FontPoint(19.0, 17.0));
		fontSegment.add(new FontPoint(19.0, 12.0));
		fontSegment.add(new FontPoint(18.0, 9.0));
		fontSegment.add(new FontPoint(17.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(12.0, 21.0));
		fontSegment.add(new FontPoint(18.0, 27.0));
		fontCharacter = new FontCharacter('R', 21.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(13.0, 4.0));
		fontSegment.add(new FontPoint(16.0, 5.0));
		fontSegment.add(new FontPoint(17.0, 6.0));
		fontSegment.add(new FontPoint(18.0, 8.0));
		fontSegment.add(new FontPoint(18.0, 10.0));
		fontSegment.add(new FontPoint(17.0, 12.0));
		fontSegment.add(new FontPoint(16.0, 13.0));
		fontSegment.add(new FontPoint(13.0, 14.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(11.0, 14.0));
		fontSegment.add(new FontPoint(18.0, 25.0));
		fontCharacter = new FontCharacter('S', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 7.0));
		fontSegment.add(new FontPoint(15.0, 5.0));
		fontSegment.add(new FontPoint(12.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 5.0));
		fontSegment.add(new FontPoint(3.0, 7.0));
		fontSegment.add(new FontPoint(3.0, 9.0));
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(5.0, 12.0));
		fontSegment.add(new FontPoint(7.0, 13.0));
		fontSegment.add(new FontPoint(13.0, 15.0));
		fontSegment.add(new FontPoint(15.0, 16.0));
		fontSegment.add(new FontPoint(16.0, 17.0));
		fontSegment.add(new FontPoint(17.0, 19.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(12.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(3.0, 22.0));
		fontCharacter = new FontCharacter('T', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(1.0, 4.0));
		fontSegment.add(new FontPoint(15.0, 4.0));
		fontCharacter = new FontCharacter('U', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 19.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(7.0, 24.0));
		fontSegment.add(new FontPoint(10.0, 25.0));
		fontSegment.add(new FontPoint(12.0, 25.0));
		fontSegment.add(new FontPoint(15.0, 24.0));
		fontSegment.add(new FontPoint(17.0, 22.0));
		fontSegment.add(new FontPoint(18.0, 19.0));
		fontSegment.add(new FontPoint(18.0, 4.0));
		fontCharacter = new FontCharacter('V', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(1.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontCharacter = new FontCharacter('W', 30.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(2.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment.add(new FontPoint(14.0, 4.0));
		fontSegment.add(new FontPoint(21.0, 25.0));
		fontSegment.add(new FontPoint(29.0, 4.0));
		fontCharacter = new FontCharacter('X', 20.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 4.0));
		fontSegment.add(new FontPoint(17.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontCharacter = new FontCharacter('Y', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(1.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 14.0));
		fontSegment.add(new FontPoint(9.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(17.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 14.0));
		fontCharacter = new FontCharacter('Z', 26.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 4.0));
		fontSegment.add(new FontPoint(23.0, 4.0));
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontSegment.add(new FontPoint(23.0, 25.0));
		fontCharacter = new FontCharacter('[', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 0.0));
		fontSegment.add(new FontPoint(4.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 0.0));
		fontSegment.add(new FontPoint(5.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 0.0));
		fontSegment.add(new FontPoint(11.0, 0.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 32.0));
		fontSegment.add(new FontPoint(11.0, 32.0));
		fontCharacter = new FontCharacter('\\', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(0.0, 4.0));
		fontSegment.add(new FontPoint(14.0, 28.0));
		fontCharacter = new FontCharacter(']', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 0.0));
		fontSegment.add(new FontPoint(9.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(10.0, 0.0));
		fontSegment.add(new FontPoint(10.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 0.0));
		fontSegment.add(new FontPoint(10.0, 0.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 32.0));
		fontSegment.add(new FontPoint(10.0, 32.0));
		fontCharacter = new FontCharacter('^', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(6.0, 10.0));
		fontSegment.add(new FontPoint(8.0, 7.0));
		fontSegment.add(new FontPoint(10.0, 10.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 13.0));
		fontSegment.add(new FontPoint(8.0, 8.0));
		fontSegment.add(new FontPoint(13.0, 13.0));
		fontCharacter = new FontCharacter('_', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(0.0, 27.0));
		fontSegment.add(new FontPoint(16.0, 27.0));
		fontCharacter = new FontCharacter('`', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 4.0));
		fontSegment.add(new FontPoint(7.0, 10.0));
		fontCharacter = new FontCharacter('a', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 9.0));
		fontSegment.add(new FontPoint(8.0, 8.0));
		fontSegment.add(new FontPoint(11.0, 8.0));
		fontSegment.add(new FontPoint(13.0, 9.0));
		fontSegment.add(new FontPoint(15.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(6.0, 14.0));
		fontSegment.add(new FontPoint(8.0, 13.0));
		fontSegment.add(new FontPoint(11.0, 13.0));
		fontSegment.add(new FontPoint(15.0, 13.0));
		fontCharacter = new FontCharacter('b', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(16.0, 17.0));
		fontSegment.add(new FontPoint(16.0, 19.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontCharacter = new FontCharacter('c', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontCharacter = new FontCharacter('d', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 4.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontCharacter = new FontCharacter('e', 18.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(15.0, 17.0));
		fontSegment.add(new FontPoint(15.0, 15.0));
		fontSegment.add(new FontPoint(14.0, 13.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontCharacter = new FontCharacter('f', 12.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(10.0, 4.0));
		fontSegment.add(new FontPoint(8.0, 4.0));
		fontSegment.add(new FontPoint(6.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 8.0));
		fontSegment.add(new FontPoint(5.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(2.0, 11.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontCharacter = new FontCharacter('g', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 27.0));
		fontSegment.add(new FontPoint(14.0, 30.0));
		fontSegment.add(new FontPoint(13.0, 31.0));
		fontSegment.add(new FontPoint(11.0, 32.0));
		fontSegment.add(new FontPoint(8.0, 32.0));
		fontSegment.add(new FontPoint(6.0, 31.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontCharacter = new FontCharacter('h', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 15.0));
		fontSegment.add(new FontPoint(7.0, 12.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontSegment.add(new FontPoint(12.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 15.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontCharacter = new FontCharacter('i', 8.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 5.0));
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 3.0));
		fontSegment.add(new FontPoint(3.0, 4.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontCharacter = new FontCharacter('j', 10.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(6.0, 5.0));
		fontSegment.add(new FontPoint(7.0, 4.0));
		fontSegment.add(new FontPoint(6.0, 3.0));
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(6.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 28.0));
		fontSegment.add(new FontPoint(5.0, 31.0));
		fontSegment.add(new FontPoint(3.0, 32.0));
		fontSegment.add(new FontPoint(1.0, 32.0));
		fontCharacter = new FontCharacter('k', 17.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(14.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 21.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 17.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontCharacter = new FontCharacter('l', 8.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 4.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontCharacter = new FontCharacter('m', 30.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 15.0));
		fontSegment.add(new FontPoint(7.0, 12.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontSegment.add(new FontPoint(12.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 15.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 15.0));
		fontSegment.add(new FontPoint(18.0, 12.0));
		fontSegment.add(new FontPoint(20.0, 11.0));
		fontSegment.add(new FontPoint(23.0, 11.0));
		fontSegment.add(new FontPoint(25.0, 12.0));
		fontSegment.add(new FontPoint(26.0, 15.0));
		fontSegment.add(new FontPoint(26.0, 25.0));
		fontCharacter = new FontCharacter('n', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 15.0));
		fontSegment.add(new FontPoint(7.0, 12.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontSegment.add(new FontPoint(12.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 15.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontCharacter = new FontCharacter('o', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontSegment.add(new FontPoint(16.0, 19.0));
		fontSegment.add(new FontPoint(16.0, 17.0));
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontCharacter = new FontCharacter('p', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(16.0, 17.0));
		fontSegment.add(new FontPoint(16.0, 19.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontCharacter = new FontCharacter('q', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 32.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 12.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(4.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(11.0, 25.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 22.0));
		fontCharacter = new FontCharacter('r', 13.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 17.0));
		fontSegment.add(new FontPoint(5.0, 14.0));
		fontSegment.add(new FontPoint(7.0, 12.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontSegment.add(new FontPoint(12.0, 11.0));
		fontCharacter = new FontCharacter('s', 17.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(14.0, 14.0));
		fontSegment.add(new FontPoint(13.0, 12.0));
		fontSegment.add(new FontPoint(10.0, 11.0));
		fontSegment.add(new FontPoint(7.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 12.0));
		fontSegment.add(new FontPoint(3.0, 14.0));
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(6.0, 17.0));
		fontSegment.add(new FontPoint(11.0, 18.0));
		fontSegment.add(new FontPoint(13.0, 19.0));
		fontSegment.add(new FontPoint(14.0, 21.0));
		fontSegment.add(new FontPoint(14.0, 22.0));
		fontSegment.add(new FontPoint(13.0, 24.0));
		fontSegment.add(new FontPoint(10.0, 25.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment.add(new FontPoint(4.0, 24.0));
		fontSegment.add(new FontPoint(3.0, 22.0));
		fontCharacter = new FontCharacter('t', 12.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 21.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(10.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(2.0, 11.0));
		fontSegment.add(new FontPoint(9.0, 11.0));
		fontCharacter = new FontCharacter('u', 19.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 11.0));
		fontSegment.add(new FontPoint(4.0, 21.0));
		fontSegment.add(new FontPoint(5.0, 24.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment.add(new FontPoint(10.0, 25.0));
		fontSegment.add(new FontPoint(12.0, 24.0));
		fontSegment.add(new FontPoint(15.0, 21.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(15.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontCharacter = new FontCharacter('v', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(2.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(14.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontCharacter = new FontCharacter('w', 22.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 11.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(11.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(19.0, 11.0));
		fontSegment.add(new FontPoint(15.0, 25.0));
		fontCharacter = new FontCharacter('x', 17.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(14.0, 11.0));
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontCharacter = new FontCharacter('y', 16.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(2.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(14.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 29.0));
		fontSegment.add(new FontPoint(4.0, 31.0));
		fontSegment.add(new FontPoint(2.0, 32.0));
		fontSegment.add(new FontPoint(1.0, 32.0));
		fontCharacter = new FontCharacter('z', 17.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(14.0, 11.0));
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 11.0));
		fontSegment.add(new FontPoint(14.0, 11.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 25.0));
		fontSegment.add(new FontPoint(14.0, 25.0));
		fontCharacter = new FontCharacter('{', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(9.0, 0.0));
		fontSegment.add(new FontPoint(7.0, 1.0));
		fontSegment.add(new FontPoint(6.0, 2.0));
		fontSegment.add(new FontPoint(5.0, 4.0));
		fontSegment.add(new FontPoint(5.0, 6.0));
		fontSegment.add(new FontPoint(6.0, 8.0));
		fontSegment.add(new FontPoint(7.0, 9.0));
		fontSegment.add(new FontPoint(8.0, 11.0));
		fontSegment.add(new FontPoint(8.0, 13.0));
		fontSegment.add(new FontPoint(6.0, 15.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(7.0, 1.0));
		fontSegment.add(new FontPoint(6.0, 3.0));
		fontSegment.add(new FontPoint(6.0, 5.0));
		fontSegment.add(new FontPoint(7.0, 7.0));
		fontSegment.add(new FontPoint(8.0, 8.0));
		fontSegment.add(new FontPoint(9.0, 10.0));
		fontSegment.add(new FontPoint(9.0, 12.0));
		fontSegment.add(new FontPoint(8.0, 14.0));
		fontSegment.add(new FontPoint(4.0, 16.0));
		fontSegment.add(new FontPoint(8.0, 18.0));
		fontSegment.add(new FontPoint(9.0, 20.0));
		fontSegment.add(new FontPoint(9.0, 22.0));
		fontSegment.add(new FontPoint(8.0, 24.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment.add(new FontPoint(6.0, 27.0));
		fontSegment.add(new FontPoint(6.0, 29.0));
		fontSegment.add(new FontPoint(7.0, 31.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(6.0, 17.0));
		fontSegment.add(new FontPoint(8.0, 19.0));
		fontSegment.add(new FontPoint(8.0, 21.0));
		fontSegment.add(new FontPoint(7.0, 23.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(5.0, 28.0));
		fontSegment.add(new FontPoint(6.0, 30.0));
		fontSegment.add(new FontPoint(7.0, 31.0));
		fontSegment.add(new FontPoint(9.0, 32.0));
		fontCharacter = new FontCharacter('|', 8.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(4.0, 0.0));
		fontSegment.add(new FontPoint(4.0, 32.0));
		fontCharacter = new FontCharacter('}', 14.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(5.0, 0.0));
		fontSegment.add(new FontPoint(7.0, 1.0));
		fontSegment.add(new FontPoint(8.0, 2.0));
		fontSegment.add(new FontPoint(9.0, 4.0));
		fontSegment.add(new FontPoint(9.0, 6.0));
		fontSegment.add(new FontPoint(8.0, 8.0));
		fontSegment.add(new FontPoint(7.0, 9.0));
		fontSegment.add(new FontPoint(6.0, 11.0));
		fontSegment.add(new FontPoint(6.0, 13.0));
		fontSegment.add(new FontPoint(8.0, 15.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(7.0, 1.0));
		fontSegment.add(new FontPoint(8.0, 3.0));
		fontSegment.add(new FontPoint(8.0, 5.0));
		fontSegment.add(new FontPoint(7.0, 7.0));
		fontSegment.add(new FontPoint(6.0, 8.0));
		fontSegment.add(new FontPoint(5.0, 10.0));
		fontSegment.add(new FontPoint(5.0, 12.0));
		fontSegment.add(new FontPoint(6.0, 14.0));
		fontSegment.add(new FontPoint(10.0, 16.0));
		fontSegment.add(new FontPoint(6.0, 18.0));
		fontSegment.add(new FontPoint(5.0, 20.0));
		fontSegment.add(new FontPoint(5.0, 22.0));
		fontSegment.add(new FontPoint(6.0, 24.0));
		fontSegment.add(new FontPoint(7.0, 25.0));
		fontSegment.add(new FontPoint(8.0, 27.0));
		fontSegment.add(new FontPoint(8.0, 29.0));
		fontSegment.add(new FontPoint(7.0, 31.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(8.0, 17.0));
		fontSegment.add(new FontPoint(6.0, 19.0));
		fontSegment.add(new FontPoint(6.0, 21.0));
		fontSegment.add(new FontPoint(7.0, 23.0));
		fontSegment.add(new FontPoint(8.0, 24.0));
		fontSegment.add(new FontPoint(9.0, 28.0));
		fontSegment.add(new FontPoint(8.0, 30.0));
		fontSegment.add(new FontPoint(7.0, 31.0));
		fontSegment.add(new FontPoint(5.0, 32.0));
		fontCharacter = new FontCharacter('~', 24.0);
		this.add(fontCharacter);
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 19.0));
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(4.0, 14.0));
		fontSegment.add(new FontPoint(6.0, 13.0));
		fontSegment.add(new FontPoint(8.0, 13.0));
		fontSegment.add(new FontPoint(10.0, 14.0));
		fontSegment.add(new FontPoint(14.0, 17.0));
		fontSegment.add(new FontPoint(16.0, 18.0));
		fontSegment.add(new FontPoint(18.0, 18.0));
		fontSegment.add(new FontPoint(20.0, 17.0));
		fontSegment.add(new FontPoint(21.0, 15.0));
		fontSegment = new FontSegment();
		fontCharacter.add(fontSegment);
		fontSegment.add(new FontPoint(3.0, 17.0));
		fontSegment.add(new FontPoint(4.0, 15.0));
		fontSegment.add(new FontPoint(6.0, 14.0));
		fontSegment.add(new FontPoint(8.0, 14.0));
		fontSegment.add(new FontPoint(10.0, 15.0));
		fontSegment.add(new FontPoint(14.0, 18.0));
		fontSegment.add(new FontPoint(16.0, 19.0));
		fontSegment.add(new FontPoint(18.0, 19.0));
		fontSegment.add(new FontPoint(20.0, 18.0));
		fontSegment.add(new FontPoint(21.0, 15.0));
		fontSegment.add(new FontPoint(21.0, 13.0));
	}

}
